### ISSUE TITLE
Trick play is not worked sometimes

### ISSUE THREAD

**Issue by mk93lee** [SamsungDForum/JuvoPlayer#1]
Trick play is not worked.

**Comment by pbsamsung** [comment]
Hi,
Could You please provide more details. What is Your test scenario? Which video clip You are trying to play?
PawelB

**Comment by mk93lee** [comment]
.search-word {
	BACKGROUND-COLOR: #ffee94
}
P {
	MARGIN-BOTTOM: 5px; FONT-SIZE: 10pt; FONT-FAMILY: 맑은 고딕, arial; MARGIN-TOP: 5px
}
TD {
	MARGIN-BOTTOM: 5px; FONT-SIZE: 10pt; FONT-FAMILY: 맑은 고딕, arial; MARGIN-TOP: 5px
}
LI {
	MARGIN-BOTTOM: 5px; FONT-SIZE: 10pt; FONT-FAMILY: 맑은 고딕, arial; MARGIN-TOP: 5px
}
BODY {
	FONT-SIZE: 10pt; FONT-FAMILY: 맑은 고딕, arial; MARGIN: 10px; LINE-HEIGHT: 1.4
}



P {
	MARGIN-BOTTOM: 5px; FONT-SIZE: 10pt; FONT-FAMILY: 맑은 고딕, arial; MARGIN-TOP: 5px
}




hello,
 
1) Play MPEG-DASH 
2) Press FF button
3) Press FF button
4) repreat 2~3
5) App was exited or stopped
 
--------- Original Message ---------
Sender : pbsamsung <notifications@github.com>
Date : 2018-12-13 22:19 (GMT+9)
Title : Re: [SamsungDForum/JuvoPlayer] Trick play is not worked sometimes (#1)
 
Hi,Could You please provide more details. What is Your test scenario? Which video clip You are trying to play?PawelB
—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
 
 
 






Samsung Electronics co,. ltd 
Lee, Moon-Kwang 
Tel : +82-31-277-1477
Mobile : +82-10-9530-5855

**Comment by pbsamsung** [comment]
I was trying to reproduce this issue according Your scenario description. It didn't appear on my side. If you could collect log messages during Your test execution it would help us in the investigation.
