### ISSUE TITLE
ReactNativeTizen.dll refers a forbidden assembly

### ISSUE THREAD

**Issue by aisgdevteam** [SamsungDForum/JuvoPlayer#10]
When I'm trying to launch the sample app .tpk on a retail 2019 TV set (using Visual Studio ctrl+F5 command) it fails and I'm getting a popup message:
Fail to launch Your App
[FAIL] ReactNativeTizen.dll refers a forbidden assembly directly - libecore.so.1

Additional information:
Model Number: UA43T6000AKXXV
Sofware Version: T-KTS2UABC-1113.8

**Comment by pbsamsung** [comment]
> When I'm trying to launch the sample app .tpk on a retail 2019 TV set (using Visual Studio ctrl+F5 command) it fails and I'm getting a popup message:
> Fail to launch Your App
> [FAIL] ReactNativeTizen.dll refers a forbidden assembly directly - libecore.so.1
> 
> Additional information:
> Model Number: UA43T6000AKXXV
> Sofware Version: T-KTS2UABC-1113.8

Actually, the reason that You've got this [FAIL] message is the same as in case o this issue https://github.com/SamsungDForum/JuvoPlayer/issues/6#issuecomment-636711490
To overcome it You need to register Your TV HW device and receive additional certificate file. This procedure is for the moment available only for Samsung Partner Companies. It's mandatory to use Samsung Seller Office portal for the TV registration and the additional certificate file delivery.

**Comment by aisgdevteam** [comment]
> > When I'm trying to launch the sample app .tpk on a retail 2019 TV set (using Visual Studio ctrl+F5 command) it fails and I'm getting a popup message:
> > Fail to launch Your App
> > [FAIL] ReactNativeTizen.dll refers a forbidden assembly directly - libecore.so.1
> > Additional information:
> > Model Number: UA43T6000AKXXV
> > Sofware Version: T-KTS2UABC-1113.8
> 
> Actually, the reason that You've got this [FAIL] message is the same as in case o this issue [#6 (comment)](https://github.com/SamsungDForum/JuvoPlayer/issues/6#issuecomment-636711490)
> To overcome it You need to register Your TV HW device and receive additional certificate file. This procedure is for the moment available only for Samsung Partner Companies. It's mandatory to use Samsung Seller Office portal for the TV registration and the additional certificate file delivery.

Yah thankyou for your reply.
I'm waiting for Content Manager approve my request.
