### ISSUE TITLE
Can JuvoPlayer play UDP/RTP on Samsung Tizen TV 2020?

### ISSUE THREAD

**Issue by rayzdeveloper** [SamsungDForum/JuvoPlayer#11]
Dear @pbsamsung ,
I'm developing a WebApp on TV Tizen. But it can't play UDP/RTP. When I see JuvoPlayer written by C#. I've seen your update readme. I see it can play RTSP.
But I have two link:
udp://@225.1.2.249:30120
rtp://225.1.1.240:30120

So do you give me your recommend?
Can JuvoPlayer can play UDP/RTP on TV Tizen 2020?

Thanks & Best regards

**Comment by msavvicki** [comment]
Hello

JuvoPlayer does not provide direct support for UDP/RTP playback with Multicast support - judging by provided IP addresses.

I see no direct reason why such support could not be added to JuvoPlayer, but it would require JuvoPlayer modifications on your part.

JuvoPlayer does make use of FFmpeg. If your streams are FFplay playable, you may be able to offload UDP/RTP protocol support to underlying FFmpeg library, thus minimising development efforts. JuvoPlayer Hls implementation illustrates such approach.

Best Regards,

**Comment by ppaneksamsung** [comment]
> But I have two link:
udp://@225.1.2.249:30120
rtp://225.1.1.240:30120

Unfortunately, we cannot reach your servers. Could you share the test server so we can set up it internally and eventually evaluate development effort of implementation of these protocols?

**Comment by vanthanhctit93** [comment]
Dear @ppaneksamsung,

I am so sorry. Because, we are using a local server
But, You can use any udp:// stream to work with Juvo Player

Best Regards
