### ISSUE TITLE
Unable to start debugging. Unable to establish a connection to clrdbg

### ISSUE THREAD

**Issue by johnlu0907** [SamsungDForum/JuvoPlayer#13]
I have compiled SimplePlayer project on VS 2019 and installed Tizen 3.7 latest version. 
But when installing tpk to tv emulator, I'm getting an issue as following:
`Unable to start debugging. Unable to establish a connection to clrdbg`
Please help me

**Comment by ppaneksamsung** [comment]
Hello,
Could you share more details?

- Are you able to start the app without debugger? Click on "Debug -> Start without debugging" or just press Ctrl+F5 if you use default key bindings.
- Did you set SimplePlayer.Tizen.TV as a startup project? Right click on 'SimplePlayer.Tizen.TV' in 'Solution Explorer' and select 'Set as Startup Project'.
- Did you generate a partner-level certificate and signed the app? I have only tutorial for Galaxy Watch: https://developer.samsung.com/galaxy-watch-develop/getting-certificates/install.html, but the steps are almost similar. Please remember to set 'Privilege' to 'Partner' (not 'Public').
- Please share output from 'Tizen' tab 
<img width="959" alt="tizen-studio-output" src="https://user-images.githubusercontent.com/29063919/91712201-928c4500-eb87-11ea-98e9-82fe3f8f58dd.png">

**Comment by johnlu0907** [comment]
Thanks for your helping!
I have tried to run an app without debugging and never got CLRDBG issue. But I have got an notification an app is launched but really, I can not see any app launched.
![Screenshot (1)](https://user-images.githubusercontent.com/44193715/91715573-7bb61480-ebc0-11ea-92cb-48037b609a0f.png)

**Comment by ppaneksamsung** [comment]
I see "install failed[118, -14], reason: Signature error :' error in Tizen output tab.

Did you set up certificates correctly?
Here is the brief guide:
1. Install "Samsung Certificate Extension", see: https://developer.samsung.com/galaxy-watch-develop/getting-certificates/install.html
2. Open 'Tizen Certificate Manager' and create new certificate, see: https://developer.samsung.com/galaxy-watch-develop/getting-certificates/create.html
- Device type is 'TV'
- Make sure that Emulator DUID is added to 'Add individual DUIDs' in 'Create Certificate Profile' page. Emulator DUID will be automatically added if emulator is running during creating new certificate profile.
- Privilege level needs to be **'Partner'** in 'Create Certificate Profile' page.
- You will be asked to Sign-In to Samsung account. Please create a new one if you don't have any.
3. Permit to install apps on emulator, see: https://developer.samsung.com/galaxy-watch-develop/getting-certificates/permit.html
4. In VS, go to 'Tools -> Options -> Tizen -> Certification':
- Check 'Sign the .TPK file using the following option' and select 'Use profile of Tizen Certificate Manager'.
- Make sure that Profile is set to your newly created certificate.

**Comment by pbsamsung** [comment]
You can findout the about steps here: https://developer.samsung.com/smarttv/develop/getting-started/setting-up-sdk/creating-certificates.html#creating-a-certificate-profile

**Comment by johnlu0907** [comment]
Thanks for your helping! it works for me.
