### ISSUE TITLE
JuvoPlayer does supports udp multicast?

### ISSUE THREAD

**Issue by johnlu0907** [SamsungDForum/JuvoPlayer#14]
I want to play udp multicasting streams on juvoplayer.
I have tried to test it on SimplePlayer.Tizen.TV project but it is not working for me.
JuvoPlayer does supports udp multicast?

**Comment by msavvicki** [comment]
Current version of JuvoPlayer does not support any kind of udp transport, raw nor rtsp based.

**Comment by johnlu0907** [comment]
Is it not possible supporting udp multicasting on JuvoPlayer or Samsung TV?

**Comment by pbsamsung** [comment]
> I want to play udp multicasting streams on juvoplayer.
> I have tried to test it on SimplePlayer.Tizen.TV project but it is not working for me.
> JuvoPlayer does supports udp multicast?

Hello,
To we need some more data to help You.
1) Could You please provide any sample content for testing?
2) Can You explain the specific of the environment that You ar targeting? Is it hotel TV or somthing? 
3) Is Your work related to some commercial project? Does Your Company have a partner relationship with Samsung Electronics?

**Comment by johnlu0907** [comment]
udp content address is udp://@225.1.1.13:12345
I'm developing commercial project now but it is testing on emulator currently.

**Comment by pbsamsung** [comment]
> udp content address is udp://@225.1.1.13:12345
> I'm developing commercial project now but it is testing on emulator currently.

Allright, Have You sign up to https://seller.samsungapps.com/tv/portal/main portal already? If yes - please let me know Your Group (Company) and User name out there. If not - please sign-up so we could also exchange informations which are not public.

**Comment by johnlu0907** [comment]
OK

**Comment by johnlu0907** [comment]
username is johnlu0907@outlook.com
Group name is iStreamDev

**Comment by pbsamsung** [comment]
> username is [johnlu0907@outlook.com](mailto:johnlu0907@outlook.com)
> Group name is iStreamDev

Perfect!
Now, please register a ticket on the 1:1 Q&A forum using https://seller.samsungapps.com/tv/assistance/csportal/list
Set up category to Tizen->Others 
Title: JuvoPlayer app - UDP protocol support
Detail: Enter the details of your applicaton use case scenario, test stream specification and anything You think could help us.
App: select here the app that you have uploaded as reference. It can be the same app You are trying to run on the emulator

All the rest info is optional.

**Comment by johnlu0907** [comment]
We are going to develop video player supporting UDP multicasting. But we can not see any references related to udp multicasting with tizen sdk. So firstly we are considering if possible to develop an app supporting udp or not via test project.

**Comment by ppaneksamsung** [comment]
@johnlu0907 

> udp content address is udp://@225.1.1.13:12345
Are you sure it is a publicly available content? I cannot even ping 225.1.1.13.

> We are going to develop video player supporting UDP multicasting. But we can not see any references related to udp multicasting with tizen sdk. So firstly we are considering if possible to develop an app supporting udp or not via test project.

If you are asking whether current version of JuvoPlayer does support UDP multicast, then the short answer is **NO**. We may add support for UDP multicast in the future, but currently we focus on different features. JuvoPlayer is rather a reference how to implement a player in Tizen .NET TV.

If you are asking whether it is possible to implement a video player supporting UDP multicasting on Tizen TV platform, then the answer is **probably yes**. We will not do it for you, but we can provide some guidelines where to start the research.

Firstly, we recommend to take a look at FFmpeg, because it may support UDP multicasting. JuvoPlayer contains precompiled FFmpeg libraries for Tizen TV and emulator (see https://github.com/SamsungDForum/JuvoPlayer/tree/master/JuvoPlayer/lib). We use FFmpeg for playing HLS and I think you could similarly try to play UDP multicast streams. I recommend to start looking at https://github.com/SamsungDForum/JuvoPlayer/tree/master/JuvoPlayer/DataProviders/HLS directory. Please keep in mind, there is one downside with this approach - you will not be able to modify native FFmpeg code, because Samsung doesn't provide toolchain for compiling native code.

Alternatively, you can implement UDP multicast client in pure C#. .NET runtime provides UdpClient class with multicast support (https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.udpclient). Of course, you need to know how to implement a communication protocol, but (again) FFmpeg may be helpful (see https://github.com/FFmpeg/FFmpeg/blob/master/libavformat/udp.c).

I believe you will have more questions how to put all things together. Feel free to ask.

**Comment by johnlu0907** [comment]
Thanks for your support! I will test it and let you know the result.

**Comment by johnlu0907** [comment]
ffmpeg library supported in juvoplayer does supports udp solution?

**Comment by ppaneksamsung** [comment]
I didn't check it, because I don't have any streams to test, however UDP protocol shall be supported. Here is the output of configure command:

```
[   38s] + ./configure --prefix=/usr --libdir=/usr/lib --shlibdir=/usr/lib --enable-shared --disable-static --disable-version3 --disable-devices --disable-nonfree --disable-gpl --disable-doc --disable-zlib --disable-network --disable-avdevice --disable-bsfs --disable-filters --enable-filter=buffer --enable-filter=buffersink --enable-filter=crop --enable-filter=hflip --enable-filter=lut --enable-filter=lutyuv --enable-filter=lutrgb --enable-filter=overlay --enable-filter=scale --enable-filter=transpose --enable-filter=unsharp --enable-filter=vflip --disable-protocols --disable-avresample --enable-protocol=file --disable-encoders --disable-muxers --disable-parsers --enable-parser=aac --enable-parser=h264 --enable-parser=mpegaudio --enable-parser=h263 --enable-parser=mpeg4video --enable-parser=mpegvideo --enable-parser=hevc --disable-demuxers --enable-demuxer=aac --enable-demuxer=h264 --enable-demuxer=mpegts --enable-demuxer=amr --enable-demuxer=m4v --enable-demuxer=mpegtsraw --enable-demuxer=asf --enable-demuxer=mmf --enable-demuxer=mpegvideo --enable-demuxer=avi --enable-demuxer=mov --enable-demuxer=ogg --enable-demuxer=flac --enable-demuxer=mp3 --enable-demuxer=wav --enable-demuxer=h263 --enable-demuxer=mpegps --enable-demuxer=matroska --enable-demuxer=dv --enable-demuxer=flv --enable-demuxer=rm --enable-demuxer=aiff --enable-muxer=mpeg1video --enable-muxer=mpeg2video --enable-demuxer=hevc --disable-decoders --enable-decoder=alac --enable-decoder=h264 --enable-decoder=wmv1 --enable-decoder=flac --enable-decoder=mpeg4 --enable-decoder=wmv2 --enable-decoder=h263 --enable-decoder=mpegvideo --enable-decoder=wmv3 --enable-decoder=vc1 --enable-decoder=flv --enable-decoder=rv40 --enable-decoder=h263i --enable-decoder=theora --enable-decoder=mpeg1video --enable-decoder=mpeg2video --enable-decoder=pcm_alaw --enable-decoder=pcm_mulaw --enable-decoder=msmpeg4v3 --enable-decoder=hevc --enable-encoder=libx265 --enable-encoder=h263 --enable-encoder=h263p --enable-encoder=mpeg4 --enable-decoder=bmp --enable-encoder=bmp --enable-encoder=mpeg1video --enable-encoder=mpeg2video --enable-decoder=tiff --enable-decoder=mp3 --enable-decoder=amrnb --enable-encoder=aac --enable-decoder=aac --enable-swscale --disable-yasm --enable-fft --enable-rdft --enable-mdct --enable-neon --enable-network --enable-protocol=tcp --enable-demuxer=hls --enable-demuxer=rtsp --enable-demuxer=rtp --enable-demuxer=ac3 --enable-demuxer=dash --build-suffix=-juvo --disable-mmx --extra-cflags=-mfpu=neon
[   72s] install prefix            /usr
[   72s] source path               .
[   72s] C compiler                gcc
[   72s] C library                 glibc
[   72s] ARCH                      arm (armv8-a)
[   72s] build suffix              -juvo
[   72s] big-endian                no
[   72s] runtime cpu detection     yes
[   72s] ARMv5TE enabled           yes
[   72s] ARMv6 enabled             yes
[   72s] ARMv6T2 enabled           yes
[   72s] VFP enabled               yes
[   72s] NEON enabled              yes
[   72s] THUMB enabled             yes
[   72s] debug symbols             yes
[   72s] strip symbols             yes
[   72s] optimize for size         no
[   72s] optimizations             yes
[   72s] static                    no
[   72s] shared                    yes
[   72s] postprocessing support    no
[   72s] network support           yes
[   72s] threading support         pthreads
[   72s] safe bitstream reader     yes
[   72s] texi2html enabled         no
[   72s] perl enabled              yes
[   72s] pod2man enabled           yes
[   72s] makeinfo enabled          no
[   72s] makeinfo supports HTML    no
[   72s]
[   72s] External libraries:
[   72s] iconv                  libxcb_shm              xlib
[   72s] libxcb_shape           libxcb_xfixes
[   72s]
[   72s] External libraries providing hardware acceleration:
[   72s]
[   72s] Libraries:
[   72s] avcodec                        avformat                swresample
[   72s] avfilter               avutil                  swscale
[   72s]
[   72s] Programs:
[   72s] ffmpeg                 ffprobe                 ffserver
[   72s]
[   72s] Enabled decoders:
[   72s] aac                    hevc                    rv40
[   72s] alac                   mp3                     theora
[   72s] amrnb                  mpeg1video              tiff
[   72s] bmp                    mpeg2video              vc1
[   72s] flac                   mpeg4                   vp3
[   72s] flv                    mpegvideo               wmv1
[   72s] h263                   msmpeg4v3               wmv2
[   72s] h263i                  pcm_alaw                wmv3
[   72s] h264                   pcm_mulaw
[   72s]
[   72s] Enabled encoders:
[   72s] aac                    h263p                   mpeg2video
[   72s] bmp                    mpeg1video              mpeg4
[   72s] h263
[   72s]
[   72s] Enabled hwaccels:
[   72s]
[   72s] Enabled parsers:
[   72s] aac                    h263                    mpeg4video
[   72s] ac3                    h264                    mpegaudio
[   72s] flac                   hevc                    mpegvideo
[   72s]
[   72s] Enabled demuxers:
[   72s] aac                    h264                    mpegts
[   72s] ac3                    hevc                    mpegtsraw
[   72s] aiff                   hls                     mpegvideo
[   72s] amr                    m4v                     ogg
[   72s] asf                    matroska                rm
[   72s] avi                    mmf                     rtp
[   72s] dv                     mov                     rtsp
[   72s] flac                   mp3                     sdp
[   72s] flv                    mpegps                  wav
[   72s] h263
[   72s]
[   72s] Enabled muxers:
[   72s] ffm                    mpeg1video              mpeg2video
[   72s]
[   72s] Enabled protocols:
[   72s] file                   rtp                     udp
[   72s] http                   tcp
[   72s]
[   72s] Enabled filters:
[   72s] aformat                        lut                     scale
[   72s] anull                  lutrgb                  transpose
[   72s] atrim                  lutyuv                  trim
[   72s] crop                   null                    unsharp
[   72s] format                 overlay                 vflip
[   72s] hflip
[   72s]
[   72s] Enabled bsfs:
[   72s] null
[   72s]
[   72s] Enabled indevs:
[   72s]
[   72s] Enabled outdevs:
[   72s]
[   72s] License: LGPL version 2.1 or later
```

As you see, 'udp' is listed in 'Enabled protocols'.

**Comment by johnlu0907** [comment]
UDPSocketPair in RTSP is similar to udp multicast that I'm planning. What do you think of it?

**Comment by ppaneksamsung** [comment]
There is some initial support for RTSP over UDP, but we don't test/use it. Currently, we only support RTSP over TCP, where data is interleaved with RTSP methods, see https://tools.ietf.org/html/rfc2326#page-40 for reference. If UDPSocketPair is suitable to your needs, then you can take/use/modify it.

**Comment by sunshiny-dev** [comment]
Hi
I'm very interested in above comments. 
I have tried to test rtsp mode over tcp or udp on SimplePlayer project. But it is failed.
I have analyzed the code. In Open(string url) function of AVFormatContextWrapper.cs, avfomat_open_input() function call does returns a failure value.
Could you help me this?
Thanks

**Comment by ppaneksamsung** [comment]
@sunshiny-dev 

Sure, we can help you, but we need more details. Ideally, we would like to receive reproduction steps from you, so we can check your problem on our side. If that's not possible, then could you share modifications which you made to SimplePlayer project? Could you check what is a return code of Interop.FFmpeg.avformat_open_input call?

Please share as much details as you can.
