### ISSUE TITLE
Samsung IPTV Support

### ISSUE THREAD

**Issue by azzahrah** [SamsungDForum/JuvoPlayer#2]
Hello

Is this player can developed for Samsung Smart TV Led 43Inc?

**Comment by pbsamsung** [comment]
> 
> 
> Hello
> 
> Is this player can developed for Samsung Smart TV Led 43Inc?

**Comment by azzahrah** [comment]
Hello

My customer (hospital) want to decide to buy Smart TV, so i want to find good reference which TV brand that support custom development, actually they just wanto to display DVBS general schema like this:

Satellite -> DVBS Card -> MumuDVB (Sofware) -> Samsung IPTV,

my question is this possible to read DVB source base on my schema above?

**Comment by pbsamsung** [comment]
> 
> 
> Hello
> 
> My customer (hospital) want to decide to buy Smart TV, so i want to find good reference which TV brand that support custom development, actually they just wanto to display DVBS general schema like this:
> 
> Satellite -> DVBS Card -> MumuDVB (Sofware) -> Samsung IPTV,
> 
> my question is this possible to read DVB source base on my schema above?

Hello,
As it is notified in the 'Dependencies' section, JuvoPlayer incorporates the https://github.com/ngraziano/SharpRTSP library which provides functionality of the multicast playback. There is a good chance that the output of the MuMuDVB produces streams (.ts file container) which can  be played by the JuvoPlayer. However this configuration was never tested and some unexpected side effects may appear. The media server used during the JuvoPlayer development was http://www.live555.com/. 
Again, if You think about a real commercial solution You need to contact Your local Content Manager in Samsung and discuss collaboration conditions. The JuvoPlayer app requires more than just common web application privileges so has to be developed/released by the Samsung Partner companies only. 
Best Regards,
Pawel Buczynski

**Comment by azzahrah** [comment]
Helo
Thank you for your advice, to registerto be samsung partner, iam very new with Samsung Developer so i have no imagine how to develop app for samsung Smart TV, as i read JuvoPlayer using C# as language programming, is compatible with samsung? in android ap is file used by android platform, what the file used by samsung TV, mybe you can describe?
