### ISSUE TITLE
Not able to install Xamarin JuvoPlayer with esplayer partner privilege

### ISSUE THREAD

**Issue by rockinggit** [SamsungDForum/JuvoPlayer#3]
Hi,

I have compiled JuvoPlayer with Visual Studio for Tizen with setting up all dependencies.
But when try to install on Real device or emulator it gives me below error.
install failed[118, -14], reason: Signature error :

when I remove all partner privilege from manifest file. It allows to install.

I searched on internet and found that "http://developer.samsung.com/privilege/esplay"it is partner privilege. So created partner certificates (tried both Samsung and Tizen) but still it fails.

Anybody knows the reason here ? I am stuck at this.

**Comment by pbsamsung** [comment]
Hello,
First, You need to have the partner level privilege certificate installed on the device (emulator). It has to be done using the Device Manager tool (see here https://developer.tizen.org/development/visual-studio-tools-tizen/tools/device-manager) .  
The procedure steps contains:
1) Generating a partner level certificate with Certificate Manager tool in Tizen Studio. Right after that make sure the certificate is selected in MS Visual Studio Tools->Options->Tizen->Certification->Profile box)
2) Rebuilding your application in MS Visual Studio
3) Performing a single 'Permit to install applications' operation with the Device Manager. This function is visible in the 'mouse right-click' context menu. See figure: 'Connection Explorer view' on the https://developer.tizen.org/development/visual-studio-tools-tizen/tools/device-manager page.

From now on You can rebuild and launch the application anytime without steps 1), 2) and 3)  

Please, let me know if it did work in your case.
Regards,
Paweł Buczyński

**Comment by rockinggit** [comment]
Hi Pawel,

I am already doing above all steps. Still mentioning steps in details.

Certificate Creation:-

1) Tools->Tizen->Tizen Certificate Manager - > Select profile.
2) Press +.
3) Select Samsung -> TV -> Create a new certificate profile - > "name of profile" -> Next
4) Create a new author certificate -> Enter author name and password -> select Apply same password for distributor certificate
5) Sign in to my Samsung account -> Next
6) Create a new distributor certificate -> Next
7) Privilege -> Partner
8) DUID already filled as my device is connected.-> Next
Now my certificate profile is active.

Certificate Selection for Signing:-
1) Tools->Options->Tizen->Certification
2) Checked "Sign the TPK using option" -> use profile of Tizen Certificate Manager
3) Selected profile is same as created above.

Build application:-
1) Clean build my application.

Device Manager:-
1) Device Manager -> RIght click on Device-> Permit to install app.
2) Succeed to install certificate.

Using Tpk to install: (using this step as a hack as my devices does not show on Visual Studio to run directly)
1) Go to path where TPk is build in logs.
2) Copy tpk to some shorter path like C:\User\{myUserName}. (As sdb does not allow install from longer path...don't know the reason)
3) Tools->Tizen->Tizen sdb command prompt
4) using command below logs comes.

sdb install C:\Users\rockinggit\org.tizen.example.STVXamarinApplication5.Tizen.TV-1.0.0.tpk
WARNING: Your data are to be sent over an unencrypted connection and could be read by others.
pushed org.tizen.example.STVXamarinApplication5.Tizen.TV-1.0.0.tpk      100%        437KB           0KB/s
1 file(s) pushed. 0 file(s) skipped.
C:\Users\rockinggit\org.tizen.example.STVXamarinApplication5.Tizen.TV-1.0.0.tpk   3001KB/s (447520 bytes in 0.145s)

install org.tizen.example.STVXamarinApplication5.Tizen.TV
package_path /home/owner/share/tmp/sdk_tools/org.tizen.example.STVXamarinApplication5.Tizen.TV-1.0.0.tpk
was_install_app return WAS_TRUE
app_id[org.tizen.example.STVXamarinApplication5.Tizen.TV] install start
app_id[org.tizen.example.STVXamarinApplication5.Tizen.TV] installing[11]
app_id[org.tizen.example.STVXamarinApplication5.Tizen.TV] installing[14]
app_id[org.tizen.example.STVXamarinApplication5.Tizen.TV] installing[17]
app_id[org.tizen.example.STVXamarinApplication5.Tizen.TV] installing[20]
app_id[org.tizen.example.STVXamarinApplication5.Tizen.TV] installing[22]
app_id[org.tizen.example.STVXamarinApplication5.Tizen.TV] installing[25]
app_id[org.tizen.example.STVXamarinApplication5.Tizen.TV] install failed[118, -14], reason: Signature error :
spend time for wascmd is [931]ms



I hope I am doing all steps correctly. Tried above steps with Emulator and Real Device also.Once remove privilege and do above steps again it allows to install.

**Comment by pbsamsung** [comment]
Regarding the:
 "... Using Tpk to install: (using this step as a hack as my devices does not show on Visual Studio to run directly) ..."
1) Can You 'switch on' the device (emulator) selecting it with the Device Manager (DM)? Can You see the 'switch' in the on position?
2) If the 1) is positive, try to launch Visual Studio. You should observe the IP or emulator name next to the 'start debugging' green triangle. Does it work like this?  
3) If there is something different than in 1) and 2) please make sure the Tizen Studio Tools are correctly installed.  See if the path's set in VS tools->options->Tizen->tools are correct. If so You are probably experiencing some Tizen Tools for VS installation failure. See https://developer.tizen.org/development/visual-studio-tools-tizen/installing-visual-studio-tools-tizen for help.

**Comment by rockinggit** [comment]
1) Yes...I can always access device on Device Manager (launched from Tools->Tizen->Device Manager).
2) Only problem is that I always see ProjectDebugger on Visual Studio Tool bar. screenshot attached.
3) Tools->options->Tizen->Tools paths are are correct as showing green ticks in window. and also I am able to launch all Device Manager, Certificate Manager etc. from Visual studio so they should be correct.
4) I have installed Extension required like Certificate Extension from Package Manager.
![VisualStudioToolbar](https://user-images.githubusercontent.com/50704044/57919646-80569c80-7899-11e9-8b3e-66b16ce71a1f.PNG)

And also If I add public privilege it works. only problem with partner privilege. Stuck !!!

**Comment by pbsamsung** [comment]
This is pretty strange! Actually I did never see the 'ProjectDebugger' text next to the green 'debug' icon. In my case it is:
![debugoptions](https://user-images.githubusercontent.com/43370264/57922621-71271d00-78a0-11e9-88bc-c1aaaa99ad40.jpg)
when there is no device (emulator) connected or 
![debugoptionsemulatoroson](https://user-images.githubusercontent.com/43370264/57922658-8603b080-78a0-11e9-8543-3fa3fbe87b87.jpg)
When the emulator has been launched.
Could You please share the Visual Studio's 'about' window screenshoot? When opened please scroll down the 'Installed products' list and see if there is something like: 'Tizen.STV.Extension Extension - 1.0' on the list.
Mine is like below:
![aboutvs](https://user-images.githubusercontent.com/43370264/57922828-ee529200-78a0-11e9-9477-c22f3420e6f4.jpg)
  
Do You have a 2019 TV set for testing? Is it retail version or a sample with the debug FW? Do You work for a Samsung Partner Company? What is it's name?

Pawel B

**Comment by rockinggit** [comment]
Hello Pawel,

Please check the attached screenshot.
![VisualStudioAbout](https://user-images.githubusercontent.com/50704044/57939090-cfb4c100-78c9-11e9-8501-3ac4e008501a.PNG)

Yes..I work for AirBeamTV. we are a Samsung partner company. 
Through Samsung Netherlands we bought a UE43RU7400SXXN and it is a retail version.

And regarding installation failure. I found the root cause but it is weird.
For signing purpose Visual Studio/Tizen .NET Sdk is not even picking up my created certs.
It uses default certs always in path %HOMEPATH%\.nuget\packages\tizen.net.sdk\1.0.1\certificate

For hack I created a certificate with same name and password. and copied distributor cert in default of Tizen.NET SDK and using that installation is successful.

I don't know the exact reason why it did not picks up my certificate but I have to do this for now to make it work.

**Comment by pbsamsung** [comment]
Hello,
Does it mean You can succesfully launch the basic Xamarin Forms 'hello world'? Did You try to launch the JuvoPlayerXamarin too? Please, let me know the result.
Pawel B

**Comment by rockinggit** [comment]
Hello Pawel,

I was always able to launch the basic Xamarin Forms app without partner privilege.
With this hack I am able to launch the JuvoXamarinPlayer also.
But As I select any video to play. Player window opens but nothing happens for few secs and then app exits. 

Any idea what could be the reason.
I tried with all 3 players. SimplePlayer, XamarinPlayer, OpenGL player all exits at video player windows.

I have a doubt on JuvoPlayer library dependencies. Seems some dependency of JuvoPlayer library is causing it to exit. Any idea ?

**Comment by rockinggit** [comment]
Software Version:- T-MSLDEUC-1062.1 , BT - S
As per your suggestion we will send a mail to our contact point in Netherlands regarding debug FW version.

**Comment by pbsamsung** [comment]
Hello,
In the meantime lets try to go forward with the release FW that You have already installed.
First check out if all the dependencies in NuGet node are correctly setup. Check out the JuvoPlayer and XamarinPlayer.Tizen.TV projects inside the JuvoPlayer solution tree. Make sure the NuGet names starting with Tizen.... got the 'ExcludeAssests' option value equal 'Runtime'. Samsung policy here is to reuse the 'Tizen origin libraries' already existing in the TV set FW instead of delivering it bundled with an app. See below the sample picture that illustartes what I mean (Tizen.. libs are marked blue, ExcludeAssest are marked red elipsis)
![depexcludassetsruntime](https://user-images.githubusercontent.com/43370264/58174295-da8e9d80-7c9d-11e9-9900-0ebfd74a6e71.jpg)
Try to do clean project, build it again and launch. Then see if the video playback starts.

Pawel B

**Comment by rockinggit** [comment]
1) Yes I checked that in JuvoPlayer Tizen Packages has ExcludeAssets value = Runtime.
![JuvoPlayer_deps](https://user-images.githubusercontent.com/50704044/58181769-ae2e4d80-7cac-11e9-99af-215b0a08ff56.PNG)

2) But Looking at your screenshot I remember the problem i faced while compiling it.
It needed 2 dependent nuget packages. Tizen.TV.Multimedia.ESPlayer and Tizen.TV.Security which i could not find in Nuget deps and no reference on Internet.
So I tried a hack to edit .csproj file and comment out these dependencies.
![JuvoPlayer_csproj](https://user-images.githubusercontent.com/50704044/58181617-67d8ee80-7cac-11e9-80c2-99bcf4c08bb7.PNG)
and it compiled. Could this be a issue ? If yes why i don't find these nuget packages.

3) One more point you can see in below screenshot yellow sign on deps.
![TizenNetVersion](https://user-images.githubusercontent.com/50704044/58181945-ff3e4180-7cac-11e9-8d45-9a2dc781c56f.PNG)

It is due to version mismatch of Tizen.NET. by default it requires version >=14572. but it found 14628 which is already higher, So I don't think this could be a issue but just to let you know.
Do you see any possible reason based on above details ?

**Comment by rockinggit** [comment]
Actually I checked now in nuget packages that Tizen.NET.TV latest version 5.5.0.4997532 (which I am using because I don't have Tizen.TV.Multimedia.ESPlayer nuget package separately) contains Tizen.TV.Multimedia.ESPlayer.dll  and older version 4.4.0.1341 which you use doesn't contain  Tizen.TV.Multimedia.ESPlayer.dll.
I don't know TV FW has which one version but this seems to me cause of issue.

**Comment by pbsamsung** [comment]
Hi, You can keep the separate nugets: Tizen.TV.Multimedia.ESPlayer and Tizen.TV.Security commented out. Both are existing inside the Tizen.NET.TV ver. 5.5.0.4997532. This is some recent change in the Tizen nugets arrangements which I was not aware of. Sorry about that. It did work fine with the JuvoPlayerXamarin app on my side. After the version change you may experience issue with missing Newtonsoft library in JuvoPlayer project (build errors). In that case just install the Newtonsoft nuget for JuvoPlayer project. If the latest version won't work try to use version 10.0.3 which should be preloaded on the Tizen TV set (ExcludeAssets = Runtime setting makes the trick).

**Comment by rockinggit** [comment]
I tried above things as you said with Newtonsoft.json latest and 10.0.3 version both...didn't worked.

I just got some logs of app. If you can find some issue through logs.

"Download http://yt-dash-mse-test.commondatastorage.googleapis.com/media/car-20120827-160.mp4 671-1146 475 " } 
"Download http://yt-dash-mse-test.commondatastorage.googleapis.com/media/car-20120827-8c.mp4 592-851 259 " } 
"Regular: (00:00:00)-(00:03:01.6300000) " } 
"37 indexes http://yt-dash-mse-test.commondatastorage.googleapis.com/media/car-20120827-86.mp4 " } 
"37 indexes http://yt-dash-mse-test.commondatastorage.googleapis.com/media/car-20120827-85.mp4 " } 
"37 indexes http://yt-dash-mse-test.commondatastorage.googleapis.com/media/car-20120827-160.mp4 " } 
"19 indexes http://yt-dash-mse-test.commondatastorage.googleapis.com/media/car-20120827-8d.mp4 " } 
"37 indexes http://yt-dash-mse-test.commondatastorage.googleapis.com/media/car-20120827-89.mp4 " } 
"19 indexes http://yt-dash-mse-test.commondatastorage.googleapis.com/media/car-20120827-8b.mp4 " } 
"Segment Alignment: Audio=0 Video=0 TrimOffset=00:00:00 " } 
"19 indexes http://yt-dash-mse-test.commondatastorage.googleapis.com/media/car-20120827-8c.mp4 " } 
"37 indexes http://yt-dash-mse-test.commondatastorage.googleapis.com/media/car-20120827-87.mp4 " } 
"00:03:01.6300000 " } 
" " } 
"Audio " } 
"Audio: Dash pipeline start. " } 
"Audio: Media: und / audio (length:00:03:01.6260000) " } 
"Audio: newRepresentation set " } 
"Audio: Rep. Swap. Start Seg: [0] " } 
"Audio: DashClient start: 00:00:10 " } 
"Average Segment Duration: 00:00:09.5590000 Manifest Min. Buffer Time: 00:00:01.5000000 " } 
"TimeBufferDepth: 00:00:15 " } 
"Video " } 
"Video: Dash pipeline start. " } 
"Video: Media: und / video (length:00:03:01.4310000) " } 
"Video: newRepresentation set " } 
"Video: Rep. Swap. Start Seg: [0] " } 
"Video: DashClient start: 00:00:10 " } 
"Average Segment Duration: 00:00:04.9040000 Manifest Min. Buffer Time: 00:00:01.5000000 " } 
"TimeBufferDepth: 00:00:15 " } 
"Audio: Forcing INIT segment reload: True " } 
"Calculated download timeout is 922337203685477 " } 
"Video: Forcing INIT segment reload: True " } 
"Audio: Segment: INIT Requested. URL: http://yt-dash-mse-test.commondatastorage.googleapis.com/media/car-20120827-8b.mp4 Range: 0-591 " } 
"Audio " } 
"Calculated download timeout is 922337203685477 " } 
"Audio " } 
"Video: Segment: INIT Requested. URL: http://yt-dash-mse-test.commondatastorage.googleapis.com/media/car-20120827-160.mp4 Range: 0-670 " } 
"Audio: " } 
"Audio: Segment: INIT enqueued. " } 
"Video: Segment: INIT enqueued. " } 
"Audio: Buffer Size 00:00:15 " } 
"Video: Init Done. Poking downloadCompleted " } 
"Calculated download timeout is 922337203685477 " } 
"Audio: Init Done. Poking downloadCompleted " } 
"Audio: Segment: 0 Requested. URL: http://yt-dash-mse-test.commondatastorage.googleapis.com/media/car-20120827-8b.mp4 Range: 852-40521 " } 
"Video " } 
"Audio: Segment: 0 enqueued (00:00:00)-(00:00:10.0310000) " } 
"Video " } 
"Video: " } 
"Video: Buffer Size 00:00:15 " } 
"Audio: Data request update: 00:00:10 " } 
"Calculated download timeout is 922337203685477 " } 

"Audio: Data request update: 00:00:15 " } 
"Calculated download timeout is 922337203685477 " } 
"Video: Segment: 0 Requested. URL: http://yt-dash-mse-test.commondatastorage.googleapis.com/media/car-20120827-160.mp4 Range: 1147-62067 " } 
"Setting audio stream to 0 " }

**Comment by rockinggit** [comment]
Hello Pawel B,

Finally with some setting changes and moving back to TIzen Studio 2.2 I can see my device on Visual Studio Toolbar.

now I can see exceptions coming on Visual Studio Window. I need to check the reason of exception.

below are the logs I can see on Visual Studio.

Loaded '/opt/dotnet/runtime/System.Private.CoreLib.dll'. Cannot find or open the symbol file.
Loaded '/opt/dotnet/runtime/SOS.NETCore.dll'. Cannot find or open the symbol file.
Loaded '/opt/dotnet/runtime/System.Runtime.dll'. Cannot find or open the symbol file.
Loaded '/proc/7449/fd/22/bin/JuvoPlayerOpenGLNative.Tizen.TV.dll'. Symbols loaded.
Loaded '/opt/dotnet/csapi-tv-tizenfx/Tizen.TV.NUI.GLApplication.dll'. Cannot find or open the symbol file.
Loaded '/opt/dotnet/runtime/Tizen.Applications.UI.dll'. Cannot find or open the symbol file.
Loaded '/opt/dotnet/runtime/Tizen.Applications.Common.dll'. Cannot find or open the symbol file.
Loaded '/opt/dotnet/runtime/netstandard.dll'. Cannot find or open the symbol file.
Loaded '/proc/7449/fd/22/bin/JuvoPlayer.dll'. Symbols loaded.
Loaded '/opt/dotnet/runtime/System.Threading.dll'. Cannot find or open the symbol file.
Loaded '/opt/dotnet/runtime/Tizen.System.Information.dll'. Cannot find or open the symbol file.
Loaded '/opt/dotnet/runtime/Tizen.Log.dll'. Cannot find or open the symbol file.
Loaded '/opt/dotnet/runtime/System.Private.Uri.dll'. Cannot find or open the symbol file.
Loaded '/opt/dotnet/runtime/System.Runtime.InteropServices.dll'. Cannot find or open the symbol file.
Loaded '/opt/dotnet/runtime/System.Collections.dll'. Cannot find or open the symbol file.
Loaded '/opt/dotnet/runtime/Tizen.dll'. Cannot find or open the symbol file.
Loaded '/proc/7449/fd/22/bin/JuvoLogger.dll'. Symbols loaded.
Loaded '/opt/dotnet/runtime/System.Runtime.Extensions.dll'. Cannot find or open the symbol file.
Loaded '/opt/dotnet/runtime/System.IO.FileSystem.dll'. Cannot find or open the symbol file.
Loaded '/proc/7449/fd/22/bin/JuvoLogger.Tizen.dll'. Symbols loaded.
Loaded '/opt/dotnet/runtime/System.Linq.dll'. Cannot find or open the symbol file.
Loaded '/opt/dotnet/runtime/Newtonsoft.Json.dll'. Cannot find or open the symbol file.
Loaded '/opt/dotnet/runtime/System.Runtime.Serialization.Formatters.dll'. Cannot find or open the symbol file.
Loaded '/opt/dotnet/runtime/System.Collections.Concurrent.dll'. Cannot find or open the symbol file.
Loaded '/opt/dotnet/runtime/System.Diagnostics.TraceSource.dll'. Cannot find or open the symbol file.
Loaded '/opt/dotnet/runtime/System.Linq.Expressions.dll'. Cannot find or open the symbol file.
Loaded '/opt/dotnet/runtime/System.ComponentModel.TypeConverter.dll'. Cannot find or open the symbol file.
Loaded '/opt/dotnet/runtime/System.Runtime.Numerics.dll'. Cannot find or open the symbol file.
Loaded '/opt/dotnet/runtime/System.Runtime.Serialization.Primitives.dll'. Cannot find or open the symbol file.
Loaded '/opt/dotnet/runtime/System.ObjectModel.dll'. Cannot find or open the symbol file.
Loaded '/opt/dotnet/runtime/System.Data.Common.dll'. Cannot find or open the symbol file.
Loaded '/opt/dotnet/runtime/System.Xml.ReaderWriter.dll'. Cannot find or open the symbol file.
Loaded '/opt/dotnet/runtime/System.Private.Xml.dll'. Cannot find or open the symbol file.
Loaded '/opt/dotnet/runtime/System.ComponentModel.Primitives.dll'. Cannot find or open the symbol file.
Loaded '/opt/dotnet/runtime/System.ComponentModel.dll'. Cannot find or open the symbol file.
Loaded 'Anonymously Hosted DynamicMethods Assembly'. Cannot find or open the symbol file.
Loaded '/opt/dotnet/runtime/System.Collections.Specialized.dll'. Cannot find or open the symbol file.
Loaded '/opt/dotnet/runtime/System.Drawing.Primitives.dll'. Cannot find or open the symbol file.
Loaded '/opt/dotnet/runtime/System.Diagnostics.Debug.dll'. Cannot find or open the symbol file.
Loaded '/proc/7449/fd/22/bin/ImageSharp.dll'. Cannot find or open the symbol file.
Loaded '/opt/dotnet/runtime/System.Numerics.Vectors.dll'. Cannot find or open the symbol file.
Loaded '/opt/dotnet/runtime/System.IO.dll'. Cannot find or open the symbol file.
Loaded '/opt/dotnet/runtime/System.Threading.Tasks.Parallel.dll'. Cannot find or open the symbol file.
Loaded '/opt/dotnet/runtime/System.Buffers.dll'. Cannot find or open the symbol file.
Loaded '/opt/dotnet/runtime/System.Text.Encoding.dll'. Cannot find or open the symbol file.
Loaded '/proc/7449/fd/22/bin/System.Runtime.CompilerServices.Unsafe.dll'. Cannot find or open the symbol file.
Loaded '/opt/dotnet/runtime/System.IO.Compression.dll'. Cannot find or open the symbol file.
Loaded '/opt/dotnet/runtime/System.Memory.dll'. Cannot find or open the symbol file.
Loaded '/opt/dotnet/runtime/System.Threading.Tasks.dll'. Cannot find or open the symbol file.
Loaded '/opt/dotnet/runtime/System.Diagnostics.Tracing.dll'. Cannot find or open the symbol file.
Loaded '/opt/dotnet/runtime/ElmSharp.dll'. Cannot find or open the symbol file.
Loaded '/proc/7449/fd/22/bin/System.Reactive.dll'. Cannot find or open the symbol file.
Loaded '/proc/7449/fd/22/bin/System.Text.Encoding.CodePages.dll'. Cannot find or open the symbol file.
Loaded '/proc/7449/fd/22/bin/Nito.AsyncEx.Coordination.dll'. Cannot find or open the symbol file.
Loaded '/proc/7449/fd/22/bin/Nito.Collections.Deque.dll'. Cannot find or open the symbol file.
Loaded '/opt/dotnet/csapi-tv-tizenfx/Tizen.TV.Multimedia.ESPlayer.dll'. Cannot find or open the symbol file.
Loaded '/opt/dotnet/runtime/System.Runtime.InteropServices.RuntimeInformation.dll'. Cannot find or open the symbol file.
Loaded '/opt/dotnet/csapi-tv-tizenfx/Tizen.TV.Security.dll'. Cannot find or open the symbol file.
Loaded '/opt/dotnet/runtime/System.Threading.Timer.dll'. Cannot find or open the symbol file.
Loaded '/proc/7449/fd/22/bin/Configuration.dll'. Symbols loaded.
Loaded '/proc/7449/fd/22/bin/Nito.AsyncEx.Context.dll'. Cannot find or open the symbol file.
Loaded '/proc/7449/fd/22/bin/Nito.Disposables.dll'. Cannot find or open the symbol file.
Loaded '/proc/7449/fd/22/bin/Nito.AsyncEx.Tasks.dll'. Cannot find or open the symbol file.
Loaded '/opt/dotnet/runtime/System.Net.Http.dll'. Cannot find or open the symbol file.
Loaded '/opt/dotnet/runtime/System.Net.Primitives.dll'. Cannot find or open the symbol file.
Loaded '/opt/dotnet/runtime/System.Net.Security.dll'. Cannot find or open the symbol file.
Loaded '/opt/dotnet/runtime/System.Security.Cryptography.X509Certificates.dll'. Cannot find or open the symbol file.
Loaded '/opt/dotnet/runtime/System.Security.Cryptography.Primitives.dll'. Cannot find or open the symbol file.
Loaded '/proc/7449/fd/22/bin/MpdParser.dll'. Symbols loaded.
Loaded '/opt/dotnet/runtime/System.Diagnostics.DiagnosticSource.dll'. Cannot find or open the symbol file.
Loaded '/opt/dotnet/runtime/System.Collections.NonGeneric.dll'. Cannot find or open the symbol file.
Loaded '/opt/dotnet/runtime/System.Net.Sockets.dll'. Cannot find or open the symbol file.
Loaded '/opt/dotnet/runtime/Microsoft.Win32.Primitives.dll'. Cannot find or open the symbol file.
Loaded '/opt/dotnet/runtime/System.Net.NameResolution.dll'. Cannot find or open the symbol file.
Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in System.Private.CoreLib.dll
Exception thrown: 'System.Net.Http.HttpRequestException' in System.Net.Http.dll
Exception thrown: 'System.Net.Http.HttpRequestException' in System.Private.CoreLib.dll
Exception thrown: 'System.Net.Http.HttpRequestException' in System.Private.CoreLib.dll
Exception thrown: 'System.Net.Http.HttpRequestException' in System.Net.Http.dll
Exception thrown: 'System.Net.Http.HttpRequestException' in System.Private.CoreLib.dll
Exception thrown: 'System.Net.Http.HttpRequestException' in System.Private.CoreLib.dll
Exception thrown: 'System.Net.Http.HttpRequestException' in System.Private.CoreLib.dll
Exception thrown: 'System.OperationCanceledException' in System.Net.Http.dll
Exception thrown: 'System.OperationCanceledException' in System.Private.CoreLib.dll
Loaded '/opt/dotnet/runtime/System.Diagnostics.StackTrace.dll'. Cannot find or open the symbol file.
Loaded '/opt/dotnet/runtime/System.Reflection.Metadata.dll'. Cannot find or open the symbol file.
Loaded '/opt/dotnet/runtime/System.Collections.Immutable.dll'. Cannot find or open the symbol file.
Loaded '/opt/dotnet/runtime/System.IO.MemoryMappedFiles.dll'. Cannot find or open the symbol file.
Loaded '/opt/dotnet/runtime/System.Text.Encoding.Extensions.dll'. Cannot find or open the symbol file.
Loaded '/opt/dotnet/runtime/System.Threading.ThreadPool.dll'. Cannot find or open the symbol file.
Loaded '/opt/dotnet/runtime/System.Threading.Thread.dll'. Cannot find or open the symbol file.
Loaded '/opt/dotnet/runtime/System.Security.Cryptography.Algorithms.dll'. Cannot find or open the symbol file.
Loaded '/proc/7449/fd/22/bin/Polly.dll'. Cannot find or open the symbol file.
Loaded '/proc/7449/fd/22/bin/Overby.Extensions.AsyncBinaryReaderWriter.dll'. Cannot find or open the symbol file.
Exception thrown: 'System.InvalidOperationException' in 
The program 'sdb.exe' has exited with code 0 (0x0).

What could be the cause of error based on above exceptions ?

**Comment by rockinggit** [comment]
After debugging I found in EsStreamController.cs :: StreamPrepare after call to below line.
await player.PrepareAsync(OnReadyToStartStream).WithCancellation(token);

application crashes and no state comes back to HandlePlaybackStart in JuvoPlayerOpenGL.cs.

**Comment by pbsamsung** [comment]
The log messages that you have copied from the Visual Studio output window are not really relevant here. They are coming from the out side and it is actually common thing to see them during the app launch.
1) Did You try to launch the app without debugging on ? You can try it launching the app pressing ctrl+F5 keys combination. Let me know if the result is the same or different.
2) Which video stream are You trying to play? Is it the first one 'Google Car' or some other? Try to play other video clips to see if all are crashing the app the same way.

**Comment by rockinggit** [comment]
1) Yes...I tried without debugging also. same results.
2) Tried with all video clips but same results after buffering for a short duration on video play screen. application exits.

I have a doubt whether any specific version of .NETCore or .NETFramework is required. Versions on my machine are as given below.

![NETVersions](https://user-images.githubusercontent.com/50704044/58318573-4f85e280-7e18-11e9-94a0-fb6e04340a77.PNG)


And as It seems Tizen Studio 2.2 version is more compatible then 3.2 for Tizen .NET app development (I can see devices with Studio 2.2 version and it is recommended also : https://developer.samsung.com/tv/tizen-net-tv/getting-started/setting-up-development-environment).

Along with Tizen Studio 2.2 , Visual Studio Extension for Tizen 1.2 was launched.
https://www.tizen.org/blogs/journey2w/2018/tizen-studio-2.2-and-visual-studio-tools-tizen-1.2-release

But I can find only Extension 2.5 version and I wanted to try with 1.2 version. Could this be a issue of extension ? which version do you use ? where to get 1.2 version of this extension.

**Comment by ppaneksamsung** [comment]
@rockinggit 

Could you try disable TrustZone by commenting line:
https://github.com/SamsungDForum/JuvoPlayer/blob/1b45984d988911f21ee7f8df1e3a9f1403292a1a/JuvoPlayer/Player/EsPlayer/EsStreamController.cs#L141
and then play a clean content, like "Clean byte range MPEG DASH" or "Clean fMP4 MPEG DASH"?

Basically, you can play DRM content if TrustZone is enabled, but this requires additional certificates if the app is launched via Visual Studio.

Let us know if it helps.

**Comment by rockinggit** [comment]
Hi Pawel,

Thanks for your suggestion , after  commenting trustZone line I am able to play Clean Media files. Really thankful for your support.

**Comment by pbsamsung** [comment]
Hi,  With the above workaround (commenting out the 'trustZone' line) You can work only with clean contents. If You want to play protected streams (PlayReady, Widevine) we need to know the 'Unique Device ID' of Your TV set. Please, use the remote control and visit the Settings->Support->About This TV popup window. The value I need is right after the the : - Unique Device ID: .... . See the TV emulator screenshot below. It is better not to publish the ID on the Internet so please send it to my email address: p.buczynski@samsung.com. As soon as the Samsung security team registers the ID I'll send You back the certificate (key) with instructions how to use it.
Regards,
Pawel B
![samsungtvuidredelipsis](https://user-images.githubusercontent.com/43370264/58452599-303ccd00-8118-11e9-9d7f-422a419f760b.jpg)

**Comment by pbsamsung** [comment]
Hello @rockinggit. Can we close this thread? Is there anything more You need regarding this issue?

**Comment by rockinggit** [comment]
Hello @pbsamsung, As we need to work on clean URL's only for now. I think we don't require certificate as of now. Rest issues are solved so we can close this thread. Thanks for your support.

**Comment by pbsamsung** [comment]
Ok. Thanks for the feedback!
