### ISSUE TITLE
Question about JuvoPlayer

### ISSUE THREAD

**Issue by yassinox1234** [SamsungDForum/JuvoPlayer#31]
I would like to build an IPTV player app using JuvoPlayer. I want to ask you please is this player able to detect subtitles and closed caption (CC) in live streaming links (m3u8/ts)?
Also is it possible to play links such as (rtsp:// or rtmp://)?

I'm looking forward to get an answer as soon as possible

Best regards

**Comment by pbsamsung** [comment]
Hello,
For the moment, JuvoPlayer only supports the SRT and WebVTT subtitles formats (see the release notes on https://github.com/SamsungDForum/JuvoPlayer/blob/master/docs/release-notes.md)
Regards

**Comment by pbsamsung** [comment]
No more actions expected for this issue

**Comment by yassinox1234** [comment]
thank you and i'd like to know if JuvoPlayer support clearkey DRM?
