### ISSUE TITLE
Performance of JuvoPlayer OpenGL player

### ISSUE THREAD

**Issue by rockinggit** [SamsungDForum/JuvoPlayer#4]
Hi,

I checked with JuvoPlayer OpenGL performance is quite good with live streaming.
But because .NET is not supported on older Samsung TV, I want to achieve same using NaclPlayer.

while investigating OpenGL player if i stop OpenGL rendering just after play starts. performance decreases significantly. That means player frames are also being rendered using openGL ? or just the controls ?
I want to know how does openGL rendering is connected with eglSurface of player window.
I think it internal sharing of EGLSurface between openGL and TVGLApplication class (from ElmSharp window). 

Need this information to check feasibility of similar improvement on NaclPlayer.

**Comment by GTea3** [comment]
Hi,
I'm not sure what exactly is the cause of playback performance decrease you mention. I'll get back to you as soon as I get more information on the subject.

**Comment by mk93lee** [comment]
Hi, 
As we noticed NaCl will be deprycated. So, need to set up back-up plan. I think C# is best choice.

**Comment by GTea3** [comment]
Video player rendering is not done using OpenGL, so I don't believe changes in how UI is rendered using OpenGL should have any effect on video player performance. I could not reproduce a scenario with performance decreases after stopping rendering OpenGL frames you mention. Could you elaborate on how you achieved this if you have more questions regarding it (I've seen the discussion was in parallel carried out in NativePlayer githut issue)?
