### ISSUE TITLE
Terminated after attempt to play video

### ISSUE THREAD

**Issue by svsyscz** [SamsungDForum/JuvoPlayer#5]
Hello,
we have an issue with playing video content, the application unexpectedly terminated after attempt to play any video. We have experienced the same behavior for all three players: XamarinPlayer, OpenLG, SimplePlayer. Information bellow is for SimplePlayer project.

PREREQUISITES:
===============
Windows 10
Visual Studio Community 2017
Visual Studio Tools for Tizen, version 2.5.0.0
Packages (for SimplePlayer): http://cap.svsys.cz/public/samsung/juvoplayer/issues/201906191139-cantplay/packages.csv
Samsung TV UE43RU7472UXXH, T-MSLDEUC-1062.1
      
BUILD:
======
Log: http://cap.svsys.cz/public/samsung/juvoplayer/issues/201906191139-cantplay/build.csv

ISSUE DESCRIPTION
=================
After attempt to play any video a black screen is shown for 1-2 seconds and after the app terminated. 

Steps:
------
- start app via Visual Studio debug (F5)
- press ENTER key on RC (or select any video and press ENTER key on RC for XamarinPlayer)

Thank you for your help!

**Comment by GTea3** [comment]
Hello,

could you provide us with application runtime logs for DOTNET_LAUNCHER and JuvoPlayer tags? You can capture them in a couple of ways:
- using Tizen Log Viewer integrated with Visual Studio (Tools->Tizen->Tizen Log Viewer), by entering "DOTNET_LAUNCHER JuvoPlayer" in the "Tag" field,
- with sdb.exe tool provided in Tizen SDK directory's "tools" folder via "sdb dlog DOTNET_LAUNCHER,JuvoPlayer" command.

**Comment by svsyscz** [comment]
Hello,

thank you for your answer. We've tried to caught the log but without success. The Log Viewer window is empty during the test and sdb dlog returns "closed - waiting for device -" in an infinity loop. Could you give us a hint how get the log, please?

Thank you very much!

Info from sdb:
--------------
```
sdb version
Smart Development Bridge version 4.1.5

sdb capability
secure_protocol:enabled
intershell_support:disabled
filesync_support:pushpull
usbproto_support:disabled
sockproto_support:enabled
syncwinsz_support:enabled
sdbd_rootperm:disabled
rootonoff_support:disabled
encryption_support:disabled
zone_support:disabled
multiuser_support:enabled
cpu_arch:armv7
sdk_toolpath:/home/owner/share/tmp/sdk_tools
profile_name:tv
vendor_name:Samsung
can_launch:tv-samsung
device_name:Tizen
platform_version:5.0
product_version:4.0
sdbd_version:2.2.31
sdbd_plugin_version:3.7.1_TV_REL
sdbd_cap_version:1.0
log_enable:disabled
log_path:/tmp
appcmd_support:disabled
appid2pid_support:enabled
pkgcmd_debugmode:enabled
netcoredbg_support:enabled
```

**Comment by GTea3** [comment]
The issue with playing video content may be caused by lack of certificates needed for TrustZone access when launching the app via Visual Studio. Please check if commenting following line out helps with playing nonencrypted content:
https://github.com/SamsungDForum/JuvoPlayer/blob/1b45984d988911f21ee7f8df1e3a9f1403292a1a/JuvoPlayer/Player/EsPlayer/EsStreamController.cs#L141

**Comment by svsyscz** [comment]
Yes, I can confirm. Clear content is playing after comment out that line. Thank you for your support! The issue cloud be closed.
