### ISSUE TITLE
XamarinPlayer playing error

### ISSUE THREAD

**Issue by mseo12** [SamsungDForum/JuvoPlayer#8]
Hi,

Was able to install and run application on emulator, but when clicked one of contents(clean HLS), it got errors below. Not sure if there is anything wrong while following guide.

Build was okay with the latest VS Community Version.
Unloaded JavoPlayer.OpenGL/JuvoReactNative/SimplePlayer.Tizen.TV

Exception thrown: 'System.ObjectDisposedException' in 
Exception thrown: 'System.ObjectDisposedException' in 
Exception thrown: 'System.ObjectDisposedException' in 
Exception thrown: 'System.ObjectDisposedException' in 
Exception thrown: 'System.ObjectDisposedException' in 
Exception thrown: 'System.ObjectDisposedException' in 
Exception thrown: 'System.ObjectDisposedException' in 
Exception thrown: 'System.ObjectDisposedException' in 
Loaded '/proc/8106/fd/39/bin/System.Reactive.dll'. Cannot find or open the symbol file.
Loaded '/common/usr/share/dotnet/shared/Microsoft.NETCore.App/3.0.0/System.Threading.Thread.dll'. Cannot find or open the symbol file.
Loaded '/common/usr/share/dotnet/shared/Microsoft.NETCore.App/3.0.0/System.Runtime.InteropServices.RuntimeInformation.dll'. Cannot find or open the symbol file.
Loaded '/common/usr/share/dotnet/shared/Microsoft.NETCore.App/3.0.0/System.Linq.Parallel.dll'. Cannot find or open the symbol file.
Exception thrown: 'System.InvalidOperationException' in Tizen.TV.Multimedia.ESPlayer.dll
Exception thrown: 'System.InvalidOperationException' in Tizen.TV.Multimedia.ESPlayer.dll
Exception thrown: 'System.InvalidOperationException' in Tizen.TV.Multimedia.ESPlayer.dll
Exception thrown: 'System.InvalidOperationException' in Tizen.TV.Multimedia.ESPlayer.dll
Exception thrown: 'System.InvalidOperationException' in Tizen.TV.Multimedia.ESPlayer.dll
Exception thrown: 'System.InvalidOperationException' in Tizen.TV.Multimedia.ESPlayer.dll
Exception thrown: 'System.InvalidOperationException' in Tizen.TV.Multimedia.ESPlayer.dll
Exception thrown: 'System.InvalidOperationException' in Tizen.TV.Multimedia.ESPlayer.dll
Exception thrown: 'System.InvalidOperationException' in Tizen.TV.Multimedia.ESPlayer.dll
Exception thrown: 'System.InvalidOperationException' in Tizen.TV.Multimedia.ESPlayer.dll
Exception thrown: 'System.InvalidOperationException' in Tizen.TV.Multimedia.ESPlayer.dll
Exception thrown: 'System.InvalidOperationException' in Tizen.TV.Multimedia.ESPlayer.dll
Exception thrown: 'System.InvalidOperationException' in Tizen.TV.Multimedia.ESPlayer.dll
The program 'sdb.exe' has exited with code 0 (0x0).

Thank you for your supporing!!

[build.log](https://github.com/SamsungDForum/JuvoPlayer/files/4514401/build.log)
[debug_full.log](https://github.com/SamsungDForum/JuvoPlayer/files/4514409/debug_full.log)

**Comment by mseo12** [comment]
Hi,

Still have same issue but not able to see any log when run app with Ctrl+F5(of course).
Again, it can play application contents browsing also fine, but it can't play video at all (even clean drm content).

Can we see those url are valid? what file have contents urls list?

Even XamarinPlayer.Tize.TV App alos should follow the step in main pages?
It looks like that it is for React App only not for others.
Emulator TV 2019 (Tizen 5.0) 1 to 10 and "TV set unit" section.

Thank you!

**Comment by mseo12** [comment]
Confirmed that Urls are still valid (not all). So it may not be caused by invalid url.

**Comment by GTea3** [comment]
> Confirmed that Urls are still valid (not all). So it may not be caused by invalid url.

URLs are listed in remote json file (url fields in https://raw.githubusercontent.com/ppaneksamsung/JuvoPlayer/master/Resources/videoclips.json); json's file url is defined Configuration\Paths.cs file. Every URL except "FHD H264 MPEG-4 looped 20 hours playback" and "RTSP multicast streaming" should be working. Both of those are hosted localy for internal testing (20h content and RTSP server).

**Comment by msavvicki** [comment]
Exceptions provided in your logs: 

> Exception thrown: 'System.InvalidOperationException' in Tizen.TV.Multimedia.ESPlayer.dll

are "expected" before player starts. What is less expected, is number of those entries. This may indicate content accessibility issues.

HLS playlist URL (from aforementioned json):
http://multiplatform-f.akamaihd.net/i/multi/april11/sintel/sintel-hd_,512x288_450_b,640x360_700_b,768x432_1000_b,1024x576_1400_m,.mp4.csmil/master.m3u8

Can I as you to verify is this URL is accessible for you as well as chunks it is referring?
Simplest way may be through VLC.

**Comment by mseo12** [comment]
Yeah, I can play that Url even though there is no video output but it shows video after seek in VLC player.

**Comment by FernetMenta** [comment]
I think I am facing the same error. It fails in GetPlayingTime

```
System.InvalidOperationException: Invalid operation. message : ESPlayer GetPlayingTime is failed., code : InvalidOperator
   at Tizen.TV.Multimedia.Utility.VerifyOperation(ESPlayerErrorCodeInternal capiResult, String message) in /home/abuild/rpmbuild/BUILD/csapi-tv-multimedia-1.1.13/Tizen.TV.Multimedia.ESPlayer/Tizen.TV.Multimedia.ESPlayer/Utility.cs:line 115 occurred

```

**Comment by FernetMenta** [comment]
![image](https://user-images.githubusercontent.com/576009/80812688-b8e5a800-8bc8-11ea-951e-80a79ae719fc.png)

Does this mean JuvoPlayer won't run on TV emulator?

**Comment by gamukeat** [comment]
> ![image](https://user-images.githubusercontent.com/576009/80812688-b8e5a800-8bc8-11ea-951e-80a79ae719fc.png)
> 
> Does this mean JuvoPlayer won't run on TV emulator?

I can use Tizen.TV.Multimedia and play content on emulator 5.5 x86 (working for me)
But JuvoPlayer does'nt play on emulator, just on real device TV.
And support some format (container) like MP4, and not MKV. 
For live streaming, TS does'nt play also. At least not for me.

Thanks

**Comment by msavvicki** [comment]
Investigating further emulator playback, there's a package incompatibility in Tizen TV Emulator 5.5 (ver. 5.5.0.7) resulting in JuvoPlayer inability to play video content. 
https://github.com/SamsungDForum/JuvoPlayer#release-notes

Emulator version can be verified by inspecting emulator instance diskImage element in:
<tizen_studio_data_path>\emulator\vms\<emulator_instance_name>\vm_config.xml 

or emulator base image binary_version attribute in:
<tizen_studio_path>\platforms\tizen-5.5\tv-samsung\emulator-images\tv-samsung-5.5-x86\info.ini

**Comment by aisgdevteam** [comment]
Hi.
I think I am facing the same error.  I dont know how to fix. 

My Setup.
Microsoft Visual Studio Community 2019
Emulator tv-5.0
Tizen.NET - 6.0.0.14995
NuGet Package Manager - 5.5.0

Error:
Exception thrown: 'System.Security.Authentication.AuthenticationException' in System.Private.CoreLib.dll
Exception thrown: 'System.Net.Http.HttpRequestException' in System.Net.Http.dll
Exception thrown: 'System.Net.Http.HttpRequestException' in System.Private.CoreLib.dll
Exception thrown: 'System.Net.Http.HttpRequestException' in System.Net.Http.dll

**Comment by ppaneksamsung** [comment]
> Hi.
> I think I am facing the same error. I dont know how to fix.

Hello,

A few questions:
- could you share the reproduction steps?
- do you run your application with the debugger attached (Debug -> Start debugging F5 - in VS) or not (Debug -> Start without debugging Ctrl + F5)?
- Are you able to check which request (URL) is rejected? Does the same request succeeds on a different device in your network (like PC)? Please take a look at the documentation (https://docs.microsoft.com/en-us/dotnet/api/system.security.authentication.authenticationexception?view=netcore-3.1):

> AuthenticationException is thrown when authentication fails for an authentication stream ... The NegotiateStream and SslStream classes throw this exception when the client or server cannot be authenticated. ...
