### ISSUE TITLE
Use hijacked FFImageLoading library

### ISSUE THREAD

**Issue by AliDem** [SamsungDForum/JuvoPlayer#9]
> Hello,
Can we have an updated version of FFimageloading?
Because we have to update to use all the features like "DownsampleToViewSize",
with your version, we cannot use it.

I tried before to write, and with the latest version, and "DownsampleToViewSize" work fine, I haven't tried the rest of the features, but this one is important.

About security mechanism,
did you say that development can be disabled and once released (published) will it work on samsung televisions?
I can create a certificate with the partner level, but I don't know how to deactivate this mechanism

thank you.

**Comment by pbsamsung** [comment]
Generally - Yes, the security checkout can be disabled for development purposes. However, this option is only accessible for Samsung Partner Developers (Companies). Please, see the https://developer.samsung.com/smarttv/develop/distribute/seller-office.html describing the process. See the 'How to be a Partner' guide in the 'Essentials' section out there for more information.

**Comment by AliDem** [comment]
Hi,
I have a business and I have already requested a partnership and obtained partner status on (https://seller.samsungapps.com/tv/).
But I have no information on the processes of this style.

thank you

**Comment by pbsamsung** [comment]
Did you contact the Content Manager person in charge of Your region? If not yet, please follow the hint published here: https://developer.samsung.com/smarttv/develop/distribute/seller-office/membership/partnership-request.html

> If you do not know who your Contents Manager is, register a question with your country at "1:1 Q&A". Samsung will provide you your Contents Manager's email.
